# 1 - Création des usines

## Import des librairies et csv

On commence par importer les csv et les librairies nécessaires

In [2]:
import numpy as np
import pandas as pd
import sklearn as skl
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, mean_absolute_error

In [3]:
# Import des trains
DF_Train_01 = pd.read_csv("Data/csv/train_FD001.csv")
DF_Train_02 = pd.read_csv("Data/csv/train_FD002.csv")
DF_Train_03 = pd.read_csv("Data/csv/train_FD003.csv")
DF_Train_04 = pd.read_csv("Data/csv/train_FD004.csv")

# Import des tests
DF_Tests_01 = pd.read_csv("Data/csv/test_FD001.csv")
DF_Tests_02 = pd.read_csv("Data/csv/test_FD002.csv")
DF_Tests_03 = pd.read_csv("Data/csv/test_FD003.csv")
DF_Tests_04 = pd.read_csv("Data/csv/test_FD004.csv")

# Import des Ruls
DF_Rul_01 = pd.read_csv("Data/csv/RUL_FD001.csv")
DF_Rul_02 = pd.read_csv("Data/csv/RUL_FD002.csv")
DF_Rul_03 = pd.read_csv("Data/csv/RUL_FD003.csv")
DF_Rul_04 = pd.read_csv("Data/csv/RUL_FD004.csv")

Une fois Importer on vérifie rapidement les Données a l'interieur

In [4]:
DF_Train_01

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [5]:
DF_Train_02

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,...,183.06,2387.72,8048.56,9.3461,0.02,334,2223,100.00,14.73,8.8071
1,1,2,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,...,130.42,2387.66,8072.30,9.3774,0.02,330,2212,100.00,10.41,6.2665
2,1,3,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,...,164.22,2028.03,7864.87,10.8941,0.02,309,1915,84.93,14.08,8.6723
3,1,4,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,...,130.72,2387.61,8068.66,9.3528,0.02,329,2212,100.00,10.59,6.4701
4,1,5,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,...,164.31,2028.00,7861.23,10.8963,0.02,309,1915,84.93,14.13,8.5286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,...,314.05,2389.02,8169.64,9.3035,0.03,369,2324,100.00,24.36,14.5189
53755,260,313,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,...,371.22,2388.42,8245.36,8.7586,0.03,374,2319,100.00,28.10,16.9454
53756,260,314,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,...,163.74,2030.33,7971.25,11.0657,0.02,310,1915,84.93,14.19,8.5503
53757,260,315,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,...,164.37,2030.35,7972.47,11.0537,0.02,311,1915,84.93,14.05,8.3729
53758,260,316,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,...,183.09,2390.38,8185.35,9.3998,0.02,338,2223,100.00,14.75,8.8446

In [6]:
DF_Train_03

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0005,0.0004,100.0,518.67,642.36,1583.23,1396.84,14.62,...,522.31,2388.01,8145.32,8.4246,0.03,391,2388,100.0,39.11,23.3537
1,1,2,0.0008,-0.0003,100.0,518.67,642.50,1584.69,1396.89,14.62,...,522.42,2388.03,8152.85,8.4403,0.03,392,2388,100.0,38.99,23.4491
2,1,3,-0.0014,-0.0002,100.0,518.67,642.18,1582.35,1405.61,14.62,...,522.03,2388.00,8150.17,8.3901,0.03,391,2388,100.0,38.85,23.3669
3,1,4,-0.0020,0.0001,100.0,518.67,642.92,1585.61,1392.27,14.62,...,522.49,2388.08,8146.56,8.3878,0.03,392,2388,100.0,38.96,23.2951
4,1,5,0.0016,0.0000,100.0,518.67,641.68,1588.63,1397.65,14.62,...,522.58,2388.03,8147.80,8.3869,0.03,392,2388,100.0,39.14,23.4583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24715,100,148,-0.0016,-0.0003,100.0,518.67,643.78,1596.01,1424.11,14.62,...,519.66,2388.30,8138.08,8.5036,0.03,394,2388,100.0,38.44,22.9631
24716,100,149,0.0034,-0.0003,100.0,518.67,643.29,1596.38,1429.14,14.62,...,519.91,2388.28,8144.36,8.5174,0.03,395,2388,100.0,38.50,22.9746
24717,100,150,-0.0016,0.0004,100.0,518.67,643.84,1604.53,1431.41,14.62,...,519.44,2388.24,8135.95,8.5223,0.03,396,2388,100.0,38.39,23.0682
24718,100,151,-0.0023,0.0004,100.0,518.67,643.94,1597.56,1426.57,14.62,...,520.01,2388.26,8141.24,8.5148,0.03,395,2388,100.0,38.31,23.0753
24719,100,152,0.0000,0.0003,100.0,518.67,643.64,1599.04,1436.06,14.62,...,519.48,2388.24,8136.98,8.5150,0.03,396,2388,100.0,38.56,23.0847

In [7]:
DF_Train_04

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,129.78,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,312.59,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,129.62,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,129.80,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,164.11,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61244,249,251,9.9998,0.2500,100.0,489.05,605.33,1516.36,1315.28,10.52,...,380.16,2388.73,8185.69,8.4541,0.03,372,2319,100.00,29.11,17.5234
61245,249,252,0.0028,0.0015,100.0,518.67,643.42,1598.92,1426.77,14.62,...,535.02,2388.46,8185.47,8.2221,0.03,396,2388,100.00,39.38,23.7151
61246,249,253,0.0029,0.0000,100.0,518.67,643.68,1607.72,1430.56,14.62,...,535.41,2388.48,8193.94,8.2525,0.03,395,2388,100.00,39.78,23.8270
61247,249,254,35.0046,0.8400,100.0,449.44,555.77,1381.29,1148.18,5.48,...,187.92,2388.83,8125.64,9.0515,0.02,337,2223,100.00,15.26,9.0774
61248,249,255,42.0030,0.8400,100.0,445.00,549.85,1369.75,1147.45,3.91,...,134.32,2388.66,8144.33,9.1207,0.02,333,2212,100.00,10.66,6.4341

## Ajout des colonnes
Pour les 4 set, on voit que les Identifiant machines sont tous nommé de 1 à X. 
Ce qui veut dire que pour assembler 2 sets il faut ajotuer un point de distinction notament, le numéro de la ligne.

Dans le site du dataset on apprends les types de pannes et conditions de chaque trains :

                    1 mode de panne       2 modes de panne
                   (HPC uniquement)      (HPC + Fan)
                  ┌──────────────────┬──────────────────────┐
1 condition op.   │     FD001        │        FD003         │
                  │  (le plus simple)│  (dégradation mixte) │
                  ├──────────────────┼──────────────────────┤
6 conditions op.  │     FD002        │        FD004         │
                  │  (multi-régimes) │  (le plus complexe)  │
                  └──────────────────┴──────────────────────┘

De ce postula, Il y a 2 choix : 

Option A — Regrouper par type de machine (mode de panne)
- Usine 1 : FD001 + FD002 (machines qui tombent en panne sur le compresseur uniquement)
- Usine 2 : FD003 + FD004 (machines avec 2 composants critiques)
- Argument : dans une vraie usine, les machines d'une même ligne font le même travail → même type d'usure

Option B — Regrouper par environnement de travail (conditions opérationnelles)
- Usine 1 : FD001 + FD003 (régime stable → conditions de production fixes, ex : pièces aéronautiques très normalisées)
- Usine 2 : FD002 + FD004 (multi-régimes → production variée, changements fréquents, ex : pièces automobile en série variable)
- Argument : une usine automobile vs une usine aéronautique n'a pas les mêmes régimes de fonctionnement

Etant donnée que Mecha est une entreprise avec 2 types de domaines, je pense que l'option B est plus cohérentes.

In [8]:
# Premier essaie, création de la colonne Usine et Ligne
def Creation_Colonne(Liste, Usine, Ligne):
    for fichier in Liste:
        fichier['usine'] = Usine
        fichier['ligne_production'] = Ligne

In [9]:
def Creation_Colonne(Liste, Usine, Ligne):
    for fichier in Liste:
        fichier['usine'] = Usine
        fichier['ligne_production'] = Ligne
        fichier['machine_uid'] = fichier['machine_id'].astype(str) + '_' + str(Usine) + '_' + str(Ligne)

# FD001 (Usine 1, Ligne 1)
FD001 = [DF_Train_01, DF_Tests_01, DF_Rul_01]
Creation_Colonne(FD001, 1, 1)

# FD003 (Usine 1, Ligne 2)
FD003 = [DF_Train_03, DF_Tests_03, DF_Rul_03]
Creation_Colonne(FD003, 1, 2)

# FD002 (Usine 2, Ligne 1)
FD002 = [DF_Train_02, DF_Tests_02, DF_Rul_02]
Creation_Colonne(FD002, 2, 1)

# FD004 (Usine 2, Ligne 2)
FD004 = [DF_Train_04, DF_Tests_04, DF_Rul_04]
Creation_Colonne(FD004, 2, 2)

DF_Train_01

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s15,s16,s17,s18,s19,s20,s21,usine,ligne_production,machine_uid
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8.4195,0.03,392,2388,100.0,39.06,23.4190,1,1,1_1_1
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8.4318,0.03,392,2388,100.0,39.00,23.4236,1,1,1_1_1
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8.4178,0.03,390,2388,100.0,38.95,23.3442,1,1,1_1_1
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8.3682,0.03,392,2388,100.0,38.88,23.3739,1,1,1_1_1
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8.4294,0.03,393,2388,100.0,38.90,23.4044,1,1,1_1_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,8.4956,0.03,397,2388,100.0,38.49,22.9735,1,1,100_1_1
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,8.5139,0.03,395,2388,100.0,38.30,23.1594,1,1,100_1_1
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,8.5646,0.03,398,2388,100.0,38.44,22.9333,1,1,100_1_1
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,8.5389,0.03,395,2388,100.0,38.29,23.0640,1,1,100_1_1
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,8.5036,0.03,396,2388,100.0,38.37,23.0522,1,1,100_1_1

In [10]:
DF_Train_02

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s15,s16,s17,s18,s19,s20,s21,usine,ligne_production,machine_uid
0,1,1,34.9983,0.8400,100.0,449.44,555.32,1358.61,1137.23,5.48,...,9.3461,0.02,334,2223,100.00,14.73,8.8071,2,1,1_2_1
1,1,2,41.9982,0.8408,100.0,445.00,549.90,1353.22,1125.78,3.91,...,9.3774,0.02,330,2212,100.00,10.41,6.2665,2,1,1_2_1
2,1,3,24.9988,0.6218,60.0,462.54,537.31,1256.76,1047.45,7.05,...,10.8941,0.02,309,1915,84.93,14.08,8.6723,2,1,1_2_1
3,1,4,42.0077,0.8416,100.0,445.00,549.51,1354.03,1126.38,3.91,...,9.3528,0.02,329,2212,100.00,10.59,6.4701,2,1,1_2_1
4,1,5,25.0005,0.6203,60.0,462.54,537.07,1257.71,1047.93,7.05,...,10.8963,0.02,309,1915,84.93,14.13,8.5286,2,1,1_2_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53754,260,312,20.0037,0.7000,100.0,491.19,608.79,1495.60,1269.51,9.35,...,9.3035,0.03,369,2324,100.00,24.36,14.5189,2,1,260_2_1
53755,260,313,10.0022,0.2510,100.0,489.05,605.81,1514.32,1324.12,10.52,...,8.7586,0.03,374,2319,100.00,28.10,16.9454,2,1,260_2_1
53756,260,314,25.0041,0.6200,60.0,462.54,537.48,1276.24,1057.92,7.05,...,11.0657,0.02,310,1915,84.93,14.19,8.5503,2,1,260_2_1
53757,260,315,25.0033,0.6220,60.0,462.54,537.84,1272.95,1066.30,7.05,...,11.0537,0.02,311,1915,84.93,14.05,8.3729,2,1,260_2_1
53758,260,316,35.0036,0.8400,100.0,449.44,556.64,1374.61,1145.52,5.48,...,9.3998,0.02,338,2223,100.00,14.75,8.8446,2,1,260_2_1

Maintenant que les colonnes sont mise en place et les sets séparé. Alors on peut les assemblé

In [11]:
# Assemblage des trains

train_usine1 = pd.concat([DF_Train_01, DF_Train_03], ignore_index=True)
test_usine1  = pd.concat([DF_Tests_01, DF_Tests_03],  ignore_index=True)
rul_usine1   = pd.concat([DF_Rul_01, DF_Rul_03],   ignore_index=True)

train_usine2 = pd.concat([DF_Train_02, DF_Train_04], ignore_index=True)
test_usine2  = pd.concat([DF_Tests_02, DF_Tests_04],  ignore_index=True)
rul_usine2   = pd.concat([DF_Rul_02, DF_Rul_04],   ignore_index=True)

train_usine1

,machine_id,cycle,op_1,op_2,op_3,s1,s2,s3,s4,s5,...,s15,s16,s17,s18,s19,s20,s21,usine,ligne_production,machine_uid
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8.4195,0.03,392,2388,100.0,39.06,23.4190,1,1,1_1_1
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8.4318,0.03,392,2388,100.0,39.00,23.4236,1,1,1_1_1
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8.4178,0.03,390,2388,100.0,38.95,23.3442,1,1,1_1_1
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8.3682,0.03,392,2388,100.0,38.88,23.3739,1,1,1_1_1
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8.4294,0.03,393,2388,100.0,38.90,23.4044,1,1,1_1_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45346,100,148,-0.0016,-0.0003,100.0,518.67,643.78,1596.01,1424.11,14.62,...,8.5036,0.03,394,2388,100.0,38.44,22.9631,1,2,100_1_2
45347,100,149,0.0034,-0.0003,100.0,518.67,643.29,1596.38,1429.14,14.62,...,8.5174,0.03,395,2388,100.0,38.50,22.9746,1,2,100_1_2
45348,100,150,-0.0016,0.0004,100.0,518.67,643.84,1604.53,1431.41,14.62,...,8.5223,0.03,396,2388,100.0,38.39,23.0682,1,2,100_1_2
45349,100,151,-0.0023,0.0004,100.0,518.67,643.94,1597.56,1426.57,14.62,...,8.5148,0.03,395,2388,100.0,38.31,23.0753,1,2,100_1_2
45350,100,152,0.0000,0.0003,100.0,518.67,643.64,1599.04,1436.06,14.62,...,8.5150,0.03,396,2388,100.0,38.56,23.0847,1,2,100_1_2

In [12]:
# Le nombre de machines uniques dans le test = nombre de lignes dans le RUL ?
assert test_usine1['machine_uid'].nunique() == len(rul_usine1)

# Les machine_uid du RUL correspondent bien à ceux du test ?
assert set(rul_usine1['machine_uid']) == set(test_usine1['machine_uid'].unique())

# Taille cohérente ?
print(train_usine1.shape, test_usine1.shape, rul_usine1.shape)

(45351, 29) (29692, 29) (200, 5)

In [13]:
# Le nombre de machines uniques dans le test = nombre de lignes dans le RUL ?
assert test_usine2['machine_uid'].nunique() == len(rul_usine2)

# Les machine_uid du RUL correspondent bien à ceux du test ?
assert set(rul_usine2['machine_uid']) == set(test_usine2['machine_uid'].unique())

# Taille cohérente ?
print(train_usine2.shape, test_usine2.shape, rul_usine2.shape)

(115008, 29) (75205, 29) (507, 5)

## Renommage 

Avant d'enregistrer, il est demandé que nos dataset est un soit dans l'environnement MECHA. pour ce fait, je renomme les colonnes a l'aide du fichier PDF fournis par Kaggle

| --------------------------------- | ====== |
| Altitude / Mach                   | op_1   |
| Throttle Resolver Angle (TRA)     | op_2   |
| Altitude pressurisée              | op_3   |
| --------------------------------- | ====== |
| Température entrée fan — T2       | s1     |
| Température sortie LPC — T24      | s2     |
| Température sortie HPC — T30      | s3     |
| Température sortie LPT — T50      | s4     |
| Pression entrée fan — P2          | s5     |
| Pression bypass — P15             | s6     |
| Pression sortie HPC — P30         | s7     |
| Vitesse fan — Nf                  | s8     |
| Vitesse cœur — Nc                 | s9     |
| Rapport pression moteur — EPR     | s10    |
| Pression statique HPC — Ps30      | s11    |
| Ratio carburant/pression — phi    | s12    |
| Vitesse corrigée fan — NRf        | s13    |
| Vitesse corrigée cœur — NRc       | s14    |
| Bypass Ratio — BPR                | s15    |
| Richesse carburant — farB         | s16    |
| Soutirage HPC — htBleed           | s17    |
| Consigne vitesse fan — Nf_dmd     | s18    |
| Consigne vitesse corrigée — PCNfR | s19    |
| Débit refroid. HPT — W31          | s20    |
| Débit refroid. LPT — W32          | s21    |

In [14]:
mapping = {
    "op_1": "Altitude / Mach",
    "op_2": "Throttle Resolver Angle (TRA)",
    "op_3": "Altitude pressurisée",

    "s1": "Température entrée fan — T2",
    "s2": "Température sortie LPC — T24",
    "s3": "Température sortie HPC — T30",
    "s4": "Température sortie LPT — T50",
    "s5": "Pression entrée fan — P2",
    "s6": "Pression bypass — P15",
    "s7": "Pression sortie HPC — P30",
    "s8": "Vitesse fan — Nf",
    "s9": "Vitesse cœur — Nc",
    "s10": "Rapport pression moteur — EPR",
    "s11": "Pression statique HPC — Ps30",
    "s12": "Ratio carburant/pression — phi",
    "s13": "Vitesse corrigée fan — NRf",
    "s14": "Vitesse corrigée cœur — NRc",
    "s15": "Bypass Ratio — BPR",
    "s16": "Richesse carburant — farB",
    "s17": "Soutirage HPC — htBleed",
    "s18": "Consigne vitesse fan — Nf_dmd",
    "s19": "Consigne vitesse corrigée — PCNfR",
    "s20": "Débit refroid. HPT — W31",
    "s21": "Débit refroid. LPT — W32",
}

train_usine1 = train_usine1.rename(columns=mapping)
train_usine1

,machine_id,cycle,Altitude / Mach,Throttle Resolver Angle (TRA),Altitude pressurisée,Température entrée fan — T2,Température sortie LPC — T24,Température sortie HPC — T30,Température sortie LPT — T50,Pression entrée fan — P2,...,Bypass Ratio — BPR,Richesse carburant — farB,Soutirage HPC — htBleed,Consigne vitesse fan — Nf_dmd,Consigne vitesse corrigée — PCNfR,Débit refroid. HPT — W31,Débit refroid. LPT — W32,usine,ligne_production,machine_uid
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,8.4195,0.03,392,2388,100.0,39.06,23.4190,1,1,1_1_1
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,8.4318,0.03,392,2388,100.0,39.00,23.4236,1,1,1_1_1
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,8.4178,0.03,390,2388,100.0,38.95,23.3442,1,1,1_1_1
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,8.3682,0.03,392,2388,100.0,38.88,23.3739,1,1,1_1_1
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,8.4294,0.03,393,2388,100.0,38.90,23.4044,1,1,1_1_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45346,100,148,-0.0016,-0.0003,100.0,518.67,643.78,1596.01,1424.11,14.62,...,8.5036,0.03,394,2388,100.0,38.44,22.9631,1,2,100_1_2
45347,100,149,0.0034,-0.0003,100.0,518.67,643.29,1596.38,1429.14,14.62,...,8.5174,0.03,395,2388,100.0,38.50,22.9746,1,2,100_1_2
45348,100,150,-0.0016,0.0004,100.0,518.67,643.84,1604.53,1431.41,14.62,...,8.5223,0.03,396,2388,100.0,38.39,23.0682,1,2,100_1_2
45349,100,151,-0.0023,0.0004,100.0,518.67,643.94,1597.56,1426.57,14.62,...,8.5148,0.03,395,2388,100.0,38.31,23.0753,1,2,100_1_2
45350,100,152,0.0000,0.0003,100.0,518.67,643.64,1599.04,1436.06,14.62,...,8.5150,0.03,396,2388,100.0,38.56,23.0847,1,2,100_1_2

In [15]:
# Usine 1
test_usine1 = test_usine1.rename(columns=mapping)
rul_usine1 = rul_usine1.rename(columns=mapping)

# Usine 2
train_usine2 = train_usine2.rename(columns=mapping)
test_usine2 = test_usine2.rename(columns=mapping)
rul_usine2 = rul_usine2.rename(columns=mapping)

## Sauvegarder des fichiers

In [16]:
train_usine1.to_csv('Data/csv/train_usine1.csv', index=False)
test_usine1.to_csv('Data/csv/test_usine1.csv',   index=False)
rul_usine1.to_csv('Data/csv/rul_usine1.csv',     index=False)

train_usine2.to_csv('Data/csv/train_usine2.csv', index=False)
test_usine2.to_csv('Data/csv/test_usine2.csv',   index=False)
rul_usine2.to_csv('Data/csv/rul_usine2.csv',     index=False)